version: '3.8'
services:

  postgres1c:
    image: pg171c:latest
    container_name: pg171c
    hostname: pg171c
    domainname: pgslk.internal
    ports:
      - "5432:5432"
    volumes:
      - pg171c_data:/var/lib/1c/pgdata
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - LC_ALL=ru_RU.UTF-8
      - TZ=Europe/Moscow
      - PG_PASSWORD=${PG_PASSWORD}
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  pg171c_data: